### ISSUE TITLE
Can you provide a toy dataset to help us better understand this project?

### ISSUE THREAD

**Issue by iuype** [sharajpanwar/CC-WGAN-GP#9]
I cannot run a project without dataset support. Can you provide a toy dataset to help us better understand this project?

**Comment by sharajpanwar** [comment]
You can use [creating_sinusoidal.m](https://github.com/sharajpanwar/CC-WGAN-GP/blob/master/data_processing/creating_sinusoidal.m) to create a toy sinusoidal dataset to understand the method of this research. The research was conducted on the dataset provided by the US Army Research Laboratory under cooperative agreement. Unfortunately, I cannot make the data public. You can however find some RSVP public dataset and use it for training, of course after necessary preprocessing.
